import { StyleSheet } from 'react-native';
import { THEME } from '../../theme';

export const styles = StyleSheet.create({
  header: { alignItems: 'center' },
  circle: {
    alignSelf: 'center',
    position: 'absolute',
    marginTop: 70,
    height: 150,
    width: 150,
    opacity: 0.5,
    borderRadius: 100,
    backgroundColor: THEME.COLORS.WHITE,
  },
  weatherIcon: {
    position: 'absolute',
    width: 120,
    height: 120,
    top: 30,
    left: '49%',
    marginLeft: -85,
  },
  temperature: {
    paddingTop: 110,
    color: THEME.COLORS.GRAY_500,
    fontFamily: THEME.FONT_FAMILY.BLACK,
    fontSize: 64,
    paddingBottom: 70,
  },
  location: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  name: {
    color: THEME.COLORS.PURPLE,
    fontFamily: THEME.FONT_FAMILY.BOLD,
    fontSize: THEME.FONT_SIZE.LG,
    marginRight: 8,
  },
  cityIcon: {
    color: THEME.COLORS.PURPLE,
  },
  description: {
    color: THEME.COLORS.PURPLE,
    fontFamily: THEME.FONT_FAMILY.REGULAR,
    fontSize: THEME.FONT_SIZE.MD,
    marginBottom: 30,
    textAlign: 'center',
  },
  cards: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 12,
    paddingHorizontal: 10,
  },
  cardInfo: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '45%',
    minWidth: 150,
    height: 110,
    backgroundColor: THEME.COLORS.WHITE,
    borderRadius: 20,
    padding: 12,
    elevation: 8,
    shadowColor: THEME.COLORS.PURPLE,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  cardValue: {
    fontFamily: THEME.FONT_FAMILY.BOLD,
    fontSize: THEME.FONT_SIZE.MD,
    color: THEME.COLORS.GRAY_500,
    marginBottom: 2,
  },
  title: {
    fontFamily: THEME.FONT_FAMILY.SEMI_BOLD,
    fontSize: THEME.FONT_SIZE.SM,
    color: THEME.COLORS.GRAY_400,
    textAlign: 'center',
  },
});
